Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -53,7 +53,7 @@ jobs:
           echo "Creating folder for configuration: $CONFIG..."
           mkdir -p "$CONFIG"
           
-          # Set CONFIG as an environment variable for future steps
+          Set CONFIG as an environment variable for future steps
           echo "CONFIG=$CONFIG" >> $GITHUB_ENV
           
           echo "CONFIG set to: $CONFIG"
@@ -75,26 +75,26 @@ jobs:
           chmod a+rx "${{ env.CONFIG }}/git-repo/repo"
           echo "REPO=${{ github.workspace }}/${{ env.CONFIG }}/git-repo/repo" >> $GITHUB_ENV
 
-      # - name: Fetch Clang Toolchain
-      #   run: |
-      #     echo "Fetching Clang toolchain..."
-      #     mkdir -p "${{ env.CONFIG }}/clang"
-      #     git clone --recursive --depth=1 -b lineage-20.0 https://github.com/rifsxd/android_prebuilts_clang_kernel_linux-x86_clang-r416183b "${{ env.CONFIG }}/clang"
-      #     echo "${{ github.workspace }}/${{ env.CONFIG }}/clang/bin" >> $GITHUB_PATH
+       - name: Fetch Clang Toolchain
+         run: |
+           echo "Fetching Clang toolchain..."
+           mkdir -p "${{ env.CONFIG }}/clang"
+           git clone --recursive --depth=1 -b lineage-20.0 https://github.com/rifsxd/android_prebuilts_clang_kernel_linux-x86_clang-r416183b "${{ env.CONFIG }}/clang"
+           echo "${{ github.workspace }}/${{ env.CONFIG }}/clang/bin" >> $GITHUB_PATH
 
-      # - name: Fetch aarch64 Toolchain
-      #   run: |
-      #     echo "Fetching aarch64 toolchain..."
-      #     mkdir -p "${{ env.CONFIG }}/aarch64"
-      #     git clone --recursive --depth=1 -b lineage-19.1 https://github.com/rifsxd/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 "${{ env.CONFIG }}/aarch64"
-      #     echo "${{ github.workspace }}/${{ env.CONFIG }}/aarch64/bin" >> $GITHUB_PATH
+       - name: Fetch aarch64 Toolchain
+         run: |
+           echo "Fetching aarch64 toolchain..."
+           mkdir -p "${{ env.CONFIG }}/aarch64"
+           git clone --recursive --depth=1 -b lineage-19.1 https://github.com/rifsxd/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 "${{ env.CONFIG }}/aarch64"
+           echo "${{ github.workspace }}/${{ env.CONFIG }}/aarch64/bin" >> $GITHUB_PATH
 
-      # - name: Fetch arm Toolchain
-      #   run: |
-      #     echo "Fetching arm toolchain..."
-      #     mkdir -p "${{ env.CONFIG }}/arm"
-      #     git clone --recursive --depth=1 -b lineage-19.1 https://github.com/rifsxd/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 "${{ env.CONFIG }}/arm"
-      #     echo "${{ github.workspace }}/${{ env.CONFIG }}/arm/bin" >> $GITHUB_PATH
+       - name: Fetch arm Toolchain
+         run: |
+           echo "Fetching arm toolchain..."
+           mkdir -p "${{ env.CONFIG }}/arm"
+           git clone --recursive --depth=1 -b lineage-19.1 https://github.com/rifsxd/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9 "${{ env.CONFIG }}/arm"
+           echo "${{ github.workspace }}/${{ env.CONFIG }}/arm/bin" >> $GITHUB_PATH
 
       - name: Initialize and Sync Kernel Source
         run: |
@@ -118,10 +118,15 @@ jobs:
           cd "$CONFIG/kernel/msm-5.4"
           
           echo "Adding KernelSU..."
-          curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s next-susfs-dev
+          
+          # curl -LSs "https://raw.githubusercontent.com/KernelSU-Next/KernelSU-Next/next/kernel/setup.sh" | bash -s next-susfs-dev
+          
+          curl -LSs "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/main/kernel/setup.sh" | bash -s main
           
           git submodule update --init --recursive
-          cd KernelSU-Next/kernel
+          # cd KernelSU-Next/kernel
+          
+          cd KernelSU/kernel
           KSUN_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
           echo "KSUNVER=$KSUN_VERSION" >> $GITHUB_ENV
           sed -i "s/DKSU_VERSION=11998/DKSU_VERSION=${KSUN_VERSION}/" Makefile
@@ -148,19 +153,19 @@ jobs:
           
           echo "Applying SUSFS patches..."
           
-          # Copy SUSFS patches
+          Copy SUSFS patches
           cp "$GITHUB_WORKSPACE/Patches/susfs-reject-fixes.patch" ./kernel/msm-5.4/
           cp ./susfs4ksu/kernel_patches/50_add_susfs_in_kernel-5.4.patch ./kernel/msm-5.4/
           cp ./susfs4ksu/kernel_patches/fs/* ./kernel/msm-5.4/fs/
           cp ./susfs4ksu/kernel_patches/include/linux/* ./kernel/msm-5.4/include/linux/
-          # cp ./kernel_patches/next/0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch ./kernel/msm-5.4/KernelSU-Next
+          cp ./kernel_patches/next/0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch ./kernel/msm-5.4/KernelSU-Next
           
           cd ./kernel/msm-5.4/KernelSU-Next
           
-          # echo "Applying next SUSFS patches..."
-          # patch -p1 --forward < 0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch || true
+          echo "Applying next SUSFS patches..."
+          patch -p1 --forward < 0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch || true
           
-          # Change to common directory and apply SUSFS patch
+          Change to common directory and apply SUSFS patch
           cd ..
           patch -p1 -F 3 < 50_add_susfs_in_kernel-5.4.patch || true
           patch -p1 -F 3 < susfs-reject-fixes.patch || true
@@ -175,9 +180,9 @@ jobs:
         run: |
           echo "Changing to configuration directory: $CONFIG..."
           cd "$CONFIG/kernel/msm-5.4"
-          # Apply additional patch
-          #cp ../../../kernel_patches/69_hide_stuff.patch ./
-          #patch -p1 -F 3 < 69_hide_stuff.patch
+          Apply additional patch
+          cp ../../../kernel_patches/69_hide_stuff.patch ./
+          patch -p1 -F 3 < 69_hide_stuff.patch
 
       - name: Add SUSFS Configuration Settings
         run: |
@@ -185,13 +190,13 @@ jobs:
           cd "$CONFIG/kernel/msm-5.4"
           
           echo "Adding configuration settings to gki_defconfig..."
-          # echo "CONFIG_WERROR=n" >> ./arch/arm64/configs/gki_defconfig
+          echo "CONFIG_WERROR=n" >> ./arch/arm64/configs/gki_defconfig
           
-          # Add KSU configuration settings
+          Add KSU configuration settings
           echo "CONFIG_KSU=y" >> ./arch/arm64/configs/gki_defconfig
           echo "CONFIG_KSU_WITH_KPROBES=n" >> ./arch/arm64/configs/gki_defconfig
           
-          # Add SUSFS configuration settings
+          Add SUSFS configuration settings
           echo "CONFIG_KSU_SUSFS=y" >> ./arch/arm64/configs/gki_defconfig
           echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./arch/arm64/configs/gki_defconfig
           echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./arch/arm64/configs/gki_defconfig
@@ -209,7 +214,7 @@ jobs:
           echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./arch/arm64/configs/gki_defconfig
           echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./arch/arm64/configs/gki_defconfig
           
-          # Add additional tmpfs config setting
+          Add additional tmpfs config setting
           echo "CONFIG_TMPFS_XATTR=y" >> ./arch/arm64/configs/gki_defconfig
           echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./arch/arm64/configs/gki_defconfig
 
@@ -224,12 +229,12 @@ jobs:
           sed -i 's/CONFIG_LTO_CLANG_FULL=y/CONFIG_LTO_CLANG_THIN=y/' "./arch/arm64/configs/gki_defconfig"
           sed -i 's/CONFIG_LTO_CLANG_NONE=y/CONFIG_LTO_CLANG_THIN=y/' "./arch/arm64/configs/gki_defconfig"
           
-          # Run sed commands for modifications
+          Run sed commands for modifications
           sed -i 's/check_defconfig//' ./build.config.gki
           sed -i '$s|echo "\$res"|echo "\$res-fatalcoder524"|' ./scripts/setlocalversion
           sed -i 's/-dirty//' ./scripts/setlocalversion
          
-          # Run perl command to modify UTS_VERSION
+          Run perl command to modify UTS_VERSION
           perl -pi -e 's{UTS_VERSION="\$\(echo \$UTS_VERSION \$CONFIG_FLAGS \$TIMESTAMP \| cut -b -\$UTS_LEN\)"}{UTS_VERSION="#1 SMP PREEMPT Thu Mar 05 04:20:00 UTC 2025"}' ./scripts/mkcompile_h
 
       - name: GCC Build
@@ -243,17 +248,17 @@ jobs:
           sed -i 's/^UAPI_CFLAGS :=.*/& -Wno-gnu-variable-sized-type-not-at-end/' ./kernel/msm-5.4/usr/include/Makefile
           
           
-          # Export variables for immediate use in the shell
+          Export variables for immediate use in the shell
           export CLANG_TRIPLE=aarch64-linux-gnu-
           export ARCH=arm64
           export SUBARCH=arm64
           
-          # Append variables to $GITHUB_ENV for GitHub Actions
+          Append variables to $GITHUB_ENV for GitHub Actions
           echo "CLANG_TRIPLE=aarch64-linux-gnu-" >> $GITHUB_ENV
           echo "ARCH=arm64" >> $GITHUB_ENV
           echo "SUBARCH=arm64" >> $GITHUB_ENV
           
-          # Export build configuration variables
+          Export build configuration variables
           export BUILD_CONFIG=kernel/msm-5.4/build.config.lemonadep
           export VARIANT=qgki
           export BUILTIN=1
@@ -279,9 +284,9 @@ jobs:
           export LDGOLD=aarch64-linux-gnu-ld.gold
           export LLVM=1
           export LLVM_IAS=1
-          # export AS=aarch64-linux-gnu-as
+          export AS=aarch64-linux-gnu-as
           
-          # Append build configuration variables to $GITHUB_ENV
+          Append build configuration variables to $GITHUB_ENV
           echo "BUILD_CONFIG=kernel/msm-5.4/build.config.lemonadep" >> $GITHUB_ENV
           echo "VARIANT=qgki" >> $GITHUB_ENV
           echo "BUILTIN=1" >> $GITHUB_ENV
@@ -307,7 +312,7 @@ jobs:
           echo "LDGOLD=aarch64-linux-gnu-ld.gold" >> $GITHUB_ENV
           echo "LLVM=1" >> $GITHUB_ENV
           echo "LLVM_IAS=1" >> $GITHUB_ENV
-          # echo "AS=aarch64-linux-gnu-as" >> $GITHUB_ENV
+          echo "AS=aarch64-linux-gnu-as" >> $GITHUB_ENV
           
           LLVM=1 LLVM_IAS=1 build/build.sh -j4
 
